/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.cocosol;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
      /// TODO: implement test
    }
}
